credentials:
    transifex:
        user: USER
        pass: PASSWORD
ui:
    info: '{{info|Esta tabela é gerada automaticamente por script disponível em http://github.com/OSMBrasil/OSMBtranstats}}'
    title: Situação das Traduções
    columns:
        tool: Ferramenta
        status: Situação
        date: Verificado em
sources:
    -
        :type: :github
        :name: CheckAutopista (sem pt-br)
        :default: '[https://github.com/k1wiosm/checkautopista/blob/master/lang/translations.js#L191-L227 código-fonte]'
    -
        :type: :transifex
        :name: 'Editor ID: Core'
        :project: id-editor
        :resource: core
    -
        :type: :transifex
        :name: 'Editor ID: Presets [http://www.openstreetmap.org/user/ImreSamu/diary/26365 (no dups)]'
        :project: id-editor
        :resource: presets
    -
        :type: :transifex
        :name: HOT Tasking Manager
        :project: osm-tasking-manager2
        :resource: master
    -
        :type: :launchpad
        :name: Keepright
        :project: keepright
    -
        :type: :transifex
        :name: Level0
        :project: level0
        :resource: messages
    -
        :type: :google
        :name: GraphHopper
        :default: '[http://bit.ly/1CM61na 100%]'
    -
        :type: :launchpad
        :name: JOSM
        :project: josm
    -
        :type: :github
        :name: Mapillary
        :default: '[https://github.com/mapillary/mapillary_localization/blob/master/locales/pt-BR.coffee sources] [http://www.diffnow.com/?report=13g08 diff]'
    -
        :type: :launchpad
        :name: Merkaator
        :project: merkaartor
    -
        :type: :launchpad
        :name: 'Merkaator: Templates'
        :project: merkaartor
        :resource: templates
    -
        :type: :weblate
        :name: OSMAnd
        :project: osmand
        :resource: main
    -
        :type: :transifex
        :name: Overpass Turbo
        :project: overpass-turbo
        :resource: main
    -
        :type: :translatewiki
        :name: 'OpenStreetMap: Site'
        :project: out-osm-site
    -
        :type: :taginfo
        :name: 'OpenStreetMap: Wiki'
        :project: taginfo.openstreetmap.org
    -
        :type: :github
        :name: Taginfo
        :default: '[https://github.com/joto/taginfo/blob/master/web/i18n/pt-BR.yml código-fonte] [http://www.diffnow.com/?report=pa5fs diff]'
    -
        :type: :transifex
        :name: '[http://wheelmap.org Wheelmap - Site]'
        :project: wheelmap-website # existem 5 recursos
    -
        :type: :transifex
        :name: '[https://play.google.com/store/apps/details?id=org.wheelmap.android.online Wheelmap - Android app]'
        :project: wheelmap-android # existem 13 recursos
    -
        :type: :transifex
        :name: '[http://itunes.apple.com/de/app/wheelmap/id399239476?mt=8 Wheelmap - iOS app]'
        :project: wheelmap-iphone
        :resource: app_strings
    -
        :type: :transifex
        :name: '[https://www.transifex.com/projects/p/poichecker Wheelmap - POI Checker]'
        :project: poichecker
        :resource: default
